### ISSUE TITLE
focal point UI does not always load

### ISSUE THREAD

**Issue by stefanfoulis** [stefanfoulis/django-filer#385]
e.g in Chrome if the image detail view is openen in the django-cms sidebar.

Probably an issue with the ``.load()`` event: https://github.com/stefanfoulis/django-filer/blob/develop/filer/static/filer/js/focal_point.js#L62

@finalangel suspects it is because chrome has already loaded the image before this javascript is run. So the load event is never fired.

**Comment by yakky** [comment]
Fixed by #520
