### ISSUE TITLE
Does django-filer support StackedInline or TabularInline FilerFileField?

### ISSUE THREAD

**Issue by cho-is** [stefanfoulis/django-filer#462]
I would like to know if django-filer supports StackedInline or TabularInline FilerFileField for the admin. 

I couldn't figure out how to do it. Any help would be really appreciated.

**Comment by yakky** [comment]
Do you mean something like:

    class BaseModel(models.Model):
        name = models.CharField(max_length=200)

    class RelatedFiler(models.Model):
        basic = models.ForeignKey(BaseModel)
        image = FilerImageField()

    class RelatedInline(admin.TabularInline):
        model = RelatedFiler

    class BaseAdmin(admin.ModelAdmin):
        inlines = (RelatedInline, )
