### ISSUE TITLE
URLs of replaced files

### ISSUE THREAD

**Issue by evildmp** [stefanfoulis/django-filer#478]
Say you have a file in the filer, and a filer CMS plugin that links to it. 

The URL used by that plugin will be disseminated by users.

Now we update the file, and use Advanced > change to upload a new version for the same Filer file.

Now visitors who come to get the file via the plugin will get the new version, but ones who are using a direct URL to the file will hit the old version

I think that this only affects files with URLs generated with `randomize()` - date-based URLs don't change.

**Comment by yakky** [comment]
Why would you use the direct URL to the file?

**Comment by stefanfoulis** [comment]
I've had this request from other developers as well. Usecase would be urls used in emails or other direct download links from external systems.

+1 for an optional ``url_override`` field

**Comment by rstalbow** [comment]
I have a client asking for the same thing. Want to use the advance settings to change the file but keep the same URL

**Comment by yakky** [comment]
@rstalbow In the meantime you can write a simple function that returns a costant path by any given filename and use it in FILER_STORAGES (see http://django-filer.readthedocs.org/en/latest/settings.html#filer-storages). See https://github.com/stefanfoulis/django-filer/blob/develop/filer/utils/generate_filename.py for examples

**Comment by jvamvas** [comment]
@yakky Are you sure this works? Let's say we add a function in `generate_filename.py`:

```python
def constant_filename(instance, filename):
    return os.path.join('sharing', get_valid_filename(filename))
```

The first version of `my_image.jpg` is saved as `filer_public/sharing/my_image.jpg` But if we update the image using Advanced -> Change, a random alphanumeric string is added to the filename: `filer_public/sharing/my_image_UABRM5d.jpg`. So the URL sharing problem persists.
