### ISSUE TITLE
[Django>=1.7] FilerFolderField admin widget hidden

### ISSUE THREAD

**Issue by BertrandBordage** [stefanfoulis/django-filer#485]
If you use Django 1.7 and have a FilerFolderField in a model, the corresponding admin widget will not show up.

That’s happening since django/django@dc3d2ac98c1bcfad74d3e9523caf07e7e9fb15aa. In `fieldset.html`, a `hidden` class is added to a form row if all the contained widgets have `is_hidden = True`.

Setting `is_hidden` to `False` works fine. I’m not sure whether this attribute is useful somewhere else. I found it used 7 times in Django, and always refer to showing the field and its label. Since it’s not really a hidden field, I suggest we do that change.

**Comment by yakky** [comment]
thanks @BertrandBordage , fixed in #486

**Comment by tsbarnes** [comment]
I'm still running into this issue as of 51196fda9a7bea542b065b5ea41c99aca82b6759, but was able to fix it by setting `is_hidden` to `False` rather than just removing the `is_hidden` line.

**Comment by yakky** [comment]
@tsbarnes fixed in current develop
