### ISSUE TITLE
 MultiStorageFileField can handle only File object

### ISSUE THREAD

**Issue by radlws** [stefanfoulis/django-filer#488]
Getting this warning all of a sudden

```
filer/fields/multistorage_file.py:106: SyntaxWarning: MultiStorageFileField can handle only File objects;<function generate_filename_multistorage at 0x10288fde8> passed
  "%s passed" % upload_to, SyntaxWarning)
```

On top of the  "SyntaxWarning: FilerImageField can only be a ForeignKey to Image; filer.Image passed" warning which I think already has a fix.

This is using filer 0.98, django 1.7.2

**Comment by Bartvds** [comment]
Same here:

````
/home/vagrant/.virtualenvs/myproject/lib/python3.4/site-packages/filer/fields/multistorage_file.py:106: SyntaxWarning: MultiStorageFileField can handle only File objects;<function generate_filename_multistorage at 0xb6c03c8c> passed
  "%s passed" % upload_to, SyntaxWarning)
````

Also on django 1.7.2, filer 0.9.8

**Comment by yakky** [comment]
This should be fixed in #496

**Comment by yakky** [comment]
@radlws @Bartvds please check #496

**Comment by jonie-ingenuity** [comment]
env1.7/lib/python2.7/site-packages/filer/fields/multistorage_file.py:106: SyntaxWarning: MultiStorageFileField can handle only File objects;<function generate_filename_multistorage at 0x1092e6ed8> passed
  "%s passed" % upload_to, SyntaxWarning)

warning on me though.
