### ISSUE TITLE
CircularDependencyError when using custom Image model

### ISSUE THREAD

**Issue by BertrandBordage** [stefanfoulis/django-filer#490]
093d07357ee13d4ea830db136ef037180824ddae added a migration dependency to the swappable `Image` model.

But a custom `Image` model inherits from `File`, so `filer.0001_initial` needs to be applied before the custom `Image` model. It of course leads to a `CircularDependencyError`.

The solution is to remove that dependency. No django-filer model depends on `Image`, so it can be removed safely.

**Comment by yakky** [comment]
Could you test b37d9b7

**Comment by BertrandBordage** [comment]
It works! :)
