### ISSUE TITLE
dumping filer data with fixture give a polymorphic error

### ISSUE THREAD

**Issue by kasmihmed** [stefanfoulis/django-filer#504]
Hi,
i've tried to dumpdata with fixtures for the filer app however when i load it ,i get an:
 issubclass() arg 2 must be a class or tuple of classes

this happen when i try to access one of the folders ,
this is apparently a polymorphic problem . it would be great to know how to fix it

**Comment by yakky** [comment]
Which versions of django-polymorphic?

**Comment by kasmihmed** [comment]
Hi , after some investigation, i found a way to load fixtures in the right order.
apparently filer had some dependencies that needed to be also reflected on the way fixtures are loaded, this wasn't a django-polymorphic related problem , thank you for you support

**Comment by frnhr** [comment]
@kasmihmed I have the same issue (or al least it looks that way). Any tips? Pretty please? :smiley:

**Comment by creimers** [comment]
I am also running into this issue with an older project I'm trying to reactivate.

`django-polymorphic==0.7.2`

@kasmihmed Can you explain what exactly it was that you did upon fixture loading?

**Comment by kasmihmed** [comment]
hi @creimers and @frnhr .
you have to check the app you want to dump data for. and if that is a third party app you have to check the dependencies of that app. so if A is using B which using C that means you have to dump C first then B then A .
i hope this would help :)

**Comment by creimers** [comment]
Let me share what has worked for me:

1. `./manage.py dumpdata --natural-foreign > db_dump.json`

2. `./manage.py sqlflush |  ./manage.py dbshell` (as described in the [docs](https://django-filer.readthedocs.io/en/latest/dump_payload.html))

3. `./manage.py loaddata db_dump.json`

+ manually copying the media folder in the right location.

**Comment by MrBrownWins** [comment]
It worked perfect in my recent project.
