### ISSUE TITLE
An old version of django-mptt is pinned, breaking 1.8 support. The newest django-mptt supports Django 1.8 but filer insists on an older version.

### ISSUE THREAD

**Issue by gavinwahl** [stefanfoulis/django-filer#517]
django-filer requires django-mptt<=0.6.2, a version that doesn't support Django 1.8, despite a newer version of django-mptt that does support it being available. Why does filer require an old version of mptt?

**Comment by yakky** [comment]
mptt has a long history of breaking compatibility (for example mptt >=0.7 breaks django CMS 3.0) and as Django 1.8 support is still not available in filer, we usually are very conservative in supported mptt versions.
We're planning to add Django 1.8 support in the next weeks which declare support for mptt >= 0.7
