### ISSUE TITLE
django migrations issues with filer

### ISSUE THREAD

**Issue by radlws** [stefanfoulis/django-filer#518]
migrations_django should be renamed to migrations so don't have to include MIGRATION_MODULES in your settings and let it pick up defaults. Then rename migrations to migrations_south.

```
MIGRATION_MODULES = {'filer': 'filer.migrations_django'}
```

old users should have to specify SOUTH_MIGRATION_MODULES instead, moving forward migrations should be default for django migrations.

**Comment by yakky** [comment]
This is going to be changed in the next release.
When the Django 1.7 compatibility landed, south wasn't "aware" of the new migrations and to improve backward compatibility we opted for a conservative approach and let pre-1.7 users to use filer without any changes on their side.
Now it's time to switch :)

**Comment by yakky** [comment]
Fixed in #540
