### ISSUE TITLE
L10n: zero can be in singular form in some languages other than english.

### ISSUE THREAD

**Issue by ppomedio** [stefanfoulis/django-filer#553]
In line 29 of « /filer/templates/admin/filer/folder/directory_table.html » (and in two other files, see .po) there are two {% blocktrans}:
• « 1 folder{% plural %}{{ counter }} folders »,
• « 1 file{% plural %}{{ counter }} files ».

In languages where zero is in singular form (as in french po file: "Plural-Forms: nplurals=2; plural=(n > 1);\n") this displays « 1 file » or  « 1 folder » when the number of files/folders is zero.

Maybe it could be changed in:
• « {{ counter }} folder{% plural %}{{ counter }} folders »,
• « {{ counter }} file{% plural %}{{ counter }} files ».

Will made a pull request to propose a fix about this problem.

**Comment by ppomedio** [comment]
Related pull request is #554.


In french, it says (for the « root » one):

![capture d ecran 2015-07-07 a 15 09 31](https://cloud.githubusercontent.com/assets/10742818/8546722/52a9c424-24ba-11e5-8de4-c84e3f81bad4.png)

but there's noting in it!

![capture d ecran 2015-07-07 a 15 09 59](https://cloud.githubusercontent.com/assets/10742818/8546729/5ca11928-24ba-11e5-8d83-3f6c0ca4badd.png)

**Comment by yakky** [comment]
Fixed by #554
