### ISSUE TITLE
Cannot install PIP on LINUX

### ISSUE THREAD

**Issue by cynosure549** [stefanfoulis/django-filer#556]
Here is my setup:
Linux Kernel version: 3.0.101-0.40-default
that came with Python 2.6.9
I have installed python 2.7 in another folder.
created a symlink from new Python 2.7 installation to /usr/bin/python
then Installed IPython.
Now i wanted to install IPYTHON Notebook, but for that i think i need PIP.

So I set out to install PIP.
Here is what I get:
Collecting pip
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1be9f50>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/pip/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1be9bd0>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/pip/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1be9ed0>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/pip/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1be99d0>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/pip/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1be9810>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/pip/
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1be9990>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/pip/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1be9c90>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/pip/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1be9810>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/pip/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1be9dd0>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/pip/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1be9750>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/pip/
  Could not find a version that satisfies the requirement pip (from versions: )
No matching distribution found for pip

Any idea how i can get this PIP installed, or is there another way to install IPython Notebook, since that is the ulterior motive.

**Comment by yakky** [comment]
How is this relevant to django-filer?
