### ISSUE TITLE
Suggesting to remove unused 'thumbnail' template tags to avoid conflicts

### ISSUE THREAD

**Issue by philippeowagner** [stefanfoulis/django-filer#560]
We are currently in a dilemma. We used ``easy_thumbnails`` and we have to use ``sorl.thumbnail`` as well. These two libraries work both a bit differently and are used in a lot of 3rd party apps. The main problem with these two apps is, that they both come with a ``"thumbnail"`` template tag.
Tom Christie suggested [on stackoverflow](http://stackoverflow.com/a/8183735/485361) to create some kind of proxy package, but this does not fix the problem in the global scope. 
A better approach, basically how to use ``django-smart-load-tag``, is described [here](http://timmyomahony.com/blog/using-sorl-thumbnail-and-easy-thumbnails-same-template/). We use this in our templates and plugins/apps.

It seems others (eg. #45) have the same conflicting issues. So, what does this all mean for django-filer? 

The ``thumbnail`` tag is loaded in two files, [here](https://github.com/stefanfoulis/django-filer/blob/develop/filer/templates/admin/filer/tools/clipboard/clipboard.html#L1) and [here](https://github.com/stefanfoulis/django-filer/blob/develop/filer/templates/admin/filer/tools/clipboard/clipboard_item_rows.html#L1). As far as I can see, the tag is loaded but not used so just remove them. If it has to be re-added in the furure, I suggest to go with ``django-smart-load-tag``.

**Comment by yakky** [comment]
Filer depends on easy-thumbnail at a much deeper level and cannot use sorl.thumbnail.
Unneeded templatetags can be removed, but you cannot use filer with sorl-thumbnail; or at least you **need* easy-thumbnails for the filer backend to work: if there is any way you can make them both to coexist in the same project, filer backend is not "disturbed" by sorl

**Comment by philippeowagner** [comment]
@yakky do not at all intend to replace ``easy_thumbnails`` with ``sorl.thumbails``. We have project where  both (``easy_thumbnails`` and ``sorl.thumbails``) work together or side-by-side. There are no issues at all with that beside of the naming conflict of the ``thumbnail`` tag. Removing them in filer would remove the conflict. As already mentioned, if filer should use easy_thumbnails's ``thumbnail`` tag again in templates in the future, it could be loaded using ``django-smart-load-tag`` to avoid conflicts. 

Small changes with big impact - at least for us.

**Comment by yakky** [comment]
@philippeowagner sorry, I misunderstood your report. ``thumbnail`` is useless and I don't think it will return in the future :)
Thanks for your PR.
